@startuml
left to right direction
skinparam packageStyle rectangle
[Samsung Camera] as cam
[ZyXEL PoE Injector] as injector
[Network Switch] as NS
interface "DATA" as DATAIN
interface "PoE/DATA" as DATAOUT
interface "Power Outlet" as PO

cam - DATAOUT: <<Long Ethernet Cable>>
DATAOUT -- injector
injector - PO: <<IEC Cable>>
injector -- DATAIN
NS - DATAIN: <<Short Ethernet Cable>>
@enduml
