include::config.adoc[]
= scale-av minimalist webpage

SCALE A/V is the team that handles A/V for the http://socallinuxexpo.org[Southern California Linux Expo], an open source conference.

We consist of volunteers.  The main perks for volunteers include free admission to SCALE, learning new things, getting the bird's eye view of the conference.  And meals are covered for your shifts.

We are currently working on SCALE {scale_no}, which will be at the Pasadena Convention Center on {conference_dates}.  This will be our fourth time at this venue.

There are many volunteer opportunities for people of any skill level before, during, and after the conference.

== volunteer signup

If you are interested in volunteering with us,

* Sign up https://forms.gle/XmyaohJZc1t1XQs49[here] at your earliest convenience so we can get a good idea of what our staffing will be and whether we need to heavily recruit for certain time slots.  This form asks a number of questions specific to the A/V team and helps us gauge your skills, interests, and availability.
* Sign up for the https://lists.linuxfests.org/cgi-bin/mailman/listinfo/scale-av[scale-av mailing list].  This is we discuss things relating to A/V and where announcements will be made.  It will get busier as we get closer to SCALE.   Please feel free to ask questions and contribute your ideas.
* Sign up for the https://lists.linuxfests.org/cgi-bin/mailman/listinfo/scale-planning[scale-planning mailing list].  This is where other SCALE volunteers communicate.
* Bookmark http://socallinuxexpo.github.io/scale-av-web/[this page].  It will be a centralized place to direct people to current scale-av plans and activities.  We will be posting more information as we figure out logistical and technical issues.

== volunteer info

For more information on volunteering with the SCALE A/V team, please refer to the link:./scale-av-user-manual.html[SCALE AV User Manual].

== volunteer timeline

* Most of the before-SCALE activities involve software development and hardware hacking in addition to the usual planning.
* Tues night,Wed,  we will be setting up the conference rooms and the A/V command center.
* Thu-Sun,  we will be focused on live video and audio production and troubleshooting.  Volunteer hours are 9-7pm, but A/V support may be required for some evening events.  (NOTE: you are not expected to work the whole day, just whatever times you can manage.)
* Sun, once the conference is over,  we could use all the help we can get for tear down.  Most talks will be over by 5:30pm, but we can probably begin teardown of rooms that are no longer being used.
* After, we will have a post-mortem and finish up with any video editing tasks needed to get all the videos uploaded to Youtube.

== who are you?

You will mainly see e-mails between or from the following people

* Ilan Rabinovitch is the SCALE Conference Chair
* Michael Proctor Smith is the A/V Chair and handles the technical end with the cameras and video recording
* Lan Dang is the A/V volunteer coordinator
* Michael Starch is the Technical lead who owns the majority of the software stack and leads all troubleshooting.
