= SCaLE A/V Coordination =
:scale18x-av-user-manual.pdf: https://github.com/socallinuxexpo/scale-av-web/blob/gh-pages/scale18x-av-user-manual.pdf[scale18x-av-user-manual.pdf]
:user-manual-dir: link:user_manual/[user_manual/]
:changelog: link:user_manual/CHANGELOG.adoc/[CHANGELOG.adoc]
:scale-av-web: https://socallinuxexpo.github.io/scale-av-web/[scale-av webpage]
:scale-av-wiki: https://github.com/socallinuxexpo/scale-av-web/wiki[scale-av wiki]
:asciidoctor-homepage: https://asciidoctor.org/[Asciidoctor]
:scale-homepage: http://socallinuxexpo.org[Southern California Linux Expo]

Welcome to the SCaLE A/V Coordination GitHub repo! 

This repo contains source files that serve the dual purpose of generating the
{scale-av-web} and the {scale18x-av-user-manual.pdf}, as well as offering a
wiki and issue tracker for SCaLE A/V logistics and planning.

If you are interested in volunteering, please refer to the {scale-av-wiki}.

SCaLE A/V is the team that handles audio & visual (A/V) for the
{scale-homepage}, a volunteer-organized open-source conference. We are
currently working on SCaLE 18x, which will be held on March 5-8, 2020, at the
Pasadena Convention Center.

== Developer Notes ==

Documentation in this repo, including the {scale-av-web} and
{scale18x-av-user-manual.pdf}, were generated using {asciidoctor-homepage} - a
static-site generator for the
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc]
markup language.

== Contributing ==

Source files for the SCaLE A/V User Manual are maintained in the
{user-manual-dir} directory and published to the `gh-pages` branch. To update
the manual, simply edit the appropriate files in the {user-manual-dir}, note
the changes in {changelog}, then commit changes to the `master` branch.

== Previewing Changes ==

The following prerequisites and instructions are for installing and building
{asciidoctor-homepage}, including required dependencies, for previewing changes
made to the {scale18x-av-user-manual.pdf}.

=== Prerequisites ===

We recommend that you use https://github.com/rbenv/rbenv[rbenv] for installing
Ruby.

- Ruby 2.4+

=== Installation/Setup ===

Clone this repo, then change directory into the cloned repo:

 git clone https://github.com/socallinuxexpo/scale-av-web.git
 cd scale-av-web/

Install bundler, then bundle install dependencies:

 gem install bundler:2.1.4
 bundle install

=== Usage ===

The following will locally generate the latest revision of the {scale18x-av-user-manual.pdf}.

 asciidoctor user_manual/index.adoc -o scale18-av-user-manual.pdf -r asciidoctor-pdf -r asciidoctor-diagram -b pdf -a pdf-theme=user_manual/theme.yml

The following will locally generate an index.html, including diagrams, of the latest SCaLE A/V user manual.

 asciidoctor user_manual/index.adoc -r asciidoctor-diagram
