= SCaLE A/V Coordination =
:scale-av-user-manual-html: https://socallinuxexpo.github.io/scale-av-web/scale-av-user-manual.html[scale-av-user-manual.html]
:scale-av-user-manual-pdf: https://socallinuxexpo.github.io/scale-av-web/scale-av-user-manual.pdf[scale-av-user-manual.pdf]
:user-manual-dir: link:user_manual/[user_manual/]
:changelog: link:user_manual/CHANGELOG.adoc/[CHANGELOG.adoc]
:scale-av-web: https://socallinuxexpo.github.io/scale-av-web/[scale-av webpage]
:scale-av-wiki: https://github.com/socallinuxexpo/scale-av-web/wiki[scale-av wiki]
:asciidoctor-homepage: https://asciidoctor.org/[Asciidoctor]
:scale-homepage: http://socallinuxexpo.org[Southern California Linux Expo]

Welcome to the SCaLE A/V Coordination GitHub repo! 

This repo contains source files that serve the dual purpose of generating the
{scale-av-web}, {scale-av-user-manual-html}, and {scale-av-user-manual-pdf},
as well as offering a wiki and issue tracker for SCaLE A/V logistics and planning.

If you are interested in volunteering, please refer to the {scale-av-wiki}.

SCaLE A/V is the team that handles audio & visual (A/V) for the
{scale-homepage}, a volunteer-organized open-source conference.

== Developer Notes ==

Documentation in this repo, including the {scale-av-web}, {scale-av-user-manual-html},
and {scale-av-user-manual-pdf}, were generated using {asciidoctor-homepage}
- a static-site generator for the
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc]
markup language.

== Contributing ==

Source files for the SCaLE A/V User Manual are maintained in the
{user-manual-dir} directory and published to the `gh-pages` branch. To update
the manual, simply edit the appropriate files in the {user-manual-dir}, note
the changes in {changelog}, then commit changes to the `main` branch.

== Building the documentation locally ==

The following instructions are for building the
{scale-av-user-manual-html} & {scale-av-user-manual-pdf} documents locally.

=== Prerequisites ===

You will need to install https://podman.io/[podman] for your specific platform.

=== Cloning the repo ===

Clone this repo, then change directory into the cloned repo:

 git clone https://github.com/socallinuxexpo/scale-av-web.git
 cd scale-av-web/

=== Usage ===

The following will locally generate the {scale-av-user-manual-html} & {scale-av-user-manual-pdf} documents to the `dist/` folder.

 ./build.sh

