@startuml
left to right direction
skinparam packageStyle rectangle
[Female-Female\nXLR Coupler] as coupler
[Camera DI Box] as DIBox
[In-Room Audio Mixer] as mixer

DIBox -- coupler
note top of DIBox: Set ATT Switch to 0dB
note bottom of DIBox: Set Ground Switch to OFF
coupler -- mixer: <<Long XLR Audio Cable>>
@enduml
