@startuml
left to right direction
skinparam packageStyle rectangle
[PTZOptics Camera] as cam
[TP-LINK PoE Injector] as injector
[Network Switch] as NS
[PoE Splitter] as splitter
interface "LAN IN" as injectorIN
interface "POWER+DATA OUT" as injectorOUT
interface "POWER+DATA IN" as splitterIN
interface "Power Outlet" as PO

cam - splitter
splitter - splitterIN
splitterIN -- injectorOUT: <<Long Ethernet Cable>>
injectorOUT -- injector
injector - PO: <<AC Adapter>>
injector -- injectorIN
NS - injectorIN: <<Short Ethernet Cable>>
@enduml
