== Introduction ==

Welcome to the SCALE A/V Team! Thank you for volunteering your time to help make
SCALE the most awesome volunteer-run Linux Conference in the world (If anyone
says otherwise, they can take it up with Jess).

The A/V team is responsible for the setup and troubleshooting of the various
audio and video equipment used throughout the conference in partnership with the
Convention Center A/V vendor staff. Each room used for presentations will have a
projector that can be connected to a presenter’s laptop, a sound system for
sound reinforcement inside the room as well as a network-controlled camera with
a connection to the sound system for recording and streaming of the
presentation. A/V team members will report to and work from the A/V Network
Operations Center (NOC) where, during their shift, they may either help with the
monitoring of the video feeds of the various rooms via the Video Monitoring
System or be dispatched to the field to troubleshoot an issue with a particular
room. Volunteers should contact the A/V Team volunteer coordinator, Lan Dang,
and register both their availability for work shifts and their preferred job
assignment. Volunteers will be given access to documentation that explains the
equipment in use at the conference and basic troubleshooting tips to be
effective in the field.

=== Schedule Overview ===

SCALE {scale_no} is {conference_dates}, Thursday through Sunday. However, volunteers are
needed for setup on Wednesday as well as sometimes on Tuesday.
Tuesday (afternoon): Retrieving equipment from the off-site storage facility,
unpacking and setting up the A/V NOC, and potential room setups.
Wednesday (all day): Deployment, setup, and testing of all conference room
equipment.
Thursday-Sunday (8am-6pm): Volunteers work in shifts as monitors or field techs.
For evening events we will need one volunteer with audio mixer experience to
help run the board.
Sunday Evening: Teardown.
