= Radio Checkout and Protocol

The SCALE A/V team uses two-way radios with headsets to keep everyone working during a shift in communication with each other.
The radios are setup with two channels: A/V team and Tech Team.
At the beginning of each shift you will check out a radio if you have not already done so and you are responsible for its safe return and check in at the end of your shift/day.

== Radio Checkout Procedure

. Only pick up fully charged radios from the charging station.
(A green light in the charging cradle indicates full charge.)
. Sign up on check out sheet with your name and time that the radio has been checked out.
. You may also want to check out a headset.
Make sure to plug the headset into the radio to test if it works.
. To check a radio back in, put it back it in the charger to charge and log the check-in time on the sheet.
. If you have taken a headset, keep it until the end of SCaLE.
This is for sanitary purposes and so that you know that your headset works.
. *Please test your radio (and headset, if using one) before leaving the NOC to make sure it works properly and that you are on the correct channel!*

== Voice Technique

Communicating with a radio is an art.
Both procedure (what you say), and technique (how you say it) is important so that all appropriate parties can communicate efficiently and effectively.
In order to promote good communication, please observe the following techniques and procedures.

. Listen for other traffic before pressing the transmit button, so you don't accidentally talk over someone else who is already talking.
. Hold the transmit button down for at least a second before speaking to ensure that the beginning of your message is not cut off.
. Be aware of the position of the microphone in the radio chassis or external microphone in relation to your mouth so that you are able to transmit as clear a signal as possible, especially in noisy environments.
. Speak slowly, distinctively, and clearly, making sure not to trail off in volume.
This can take some practice.
Sometimes it may help to read numbers off digit by digit if the number is important, such as a device diagnostic reading.
When reading single alphabet letters, it might be more clear to use the phonetic alphabet (Alpha, Bravo, etc.) or simply a word that begins with that letter such as "T as in Thomas".
. When you finish transmitting a message, release the transmit button immediately to return the radio to the receiving mode.

== Voice Procedure

|===
| Phrase | Explanation

| Alice FOR Bob.
| Begin all transmissions with a preamble to identify who you are addressing and who you are.

| GO FOR Bob
| To preserve clarity, the contacted party begins their message with their name.

| Alice, are you near the ballrooms?
|

| Bob, SAY AGAIN?
OVER.
| If Alice did not understand Bob, she should request re-transmission by using the phrase "`say again`".

| Alice, are you near the ballrooms?.
|

| Bob, AFFIRMATIVE.
| Affirmative/Negative are often used in place of yes/no to prevent the single syllable words from getting cut off in transmission.
Note that affirmative/negative are responses to questions.

| Alice, can you go to Ballroom A and check the projector to see if it's on?
OVER.
|

| Bob, COPY.
I`'`'ll head over there.
| The terms Copy/Roger are used to designate that you have received the transmission.
Affirmative was not used here because Alice is signifying that she will comply with the request, despite Bob's phrasing of the command as a question out of politeness.
You may sometimes hear "`Wilco`", which is short for "`Will Comply`".
|===
