== Team Roles

=== Field Techs

Under most circumstances, presenters are capable of wiring themselves to the microphones and turning them on and off, as well as connecting their laptops to the projector system.
But should an issue arise or should a special request be made, a member of the A/V team will be dispatched to the room to attempt to assess the situation, report any complications to the A/V NOC, and with the advisement of the NOC, carry out the appropriate solution in a manner that minimizes the disruption to both the presenter and the attendees.
Generally, unless there is some technical issue that is preventing the talk from continuing, we do not go on stage and interrupt a speaker.
Team members will be assigned a walkie-talkie for their shift so that they can stay in contact with the NOC while in the field.
Certain special events such as panels, keynotes or specially configured rooms will require trained volunteers to be present in the conference room for the duration of the talk and operate an audio mixing board, adjusting audio levels to ensure quality of sound for the audience in the room.

=== Video Feed Monitors

Team members who volunteer to monitor the video feeds will work with a partner to watch the video streaming from all of the rooms that are broadcasting and use their surveillance capability to detect issues with the video stream, detect issues that may be occurring in the room such a projector malfunction, and to adjust the camera's framing so as to ensure that the camera is pointed toward the front of the room and has the presenter visible within the frame.
To see a detailed description of what Video Feed Monitors do, read the xref:/video-monitoring-procedure.adoc[Video Monitoring Procedure].
