== Video Monitoring Procedure

Always remember:

* *Make sure to cover your drinks!*
* Have the headphones on at the same time as the walkie talkie earpiece.

=== Check to see if the Speaker is centered in the frame

If not then pan/tilt the camera so that the Speaker is centered in the frame.
If a speaker keeps leaving the frame (like pacing around), then you may want to zoom out.

*Note when making camera adjustments*: Camera movement is sensitive.
There is a small delay between you pressing a button and the result showing up on screen.
Wait for this lag as you make adjustments.

Use the camera movement controls to position the Camera to show the speaker in the middle of the frame.
Use the *Set Home* button along the way, so that if you mess up and move the camera too far or the camera gets moved accidentally you can automatically move back to the last known good position by pressing the *Home* button.
If you've moved the camera to an unknown location, press *Home* to move back to the last known position.

Once the speaker is properly framed, press *Set Home* again to lock in the new position.

=== Listen to Audio of Each Room

To Hear Audio in the various rooms, click room's window.
If the video in the Operations Control window disappears or is not shown, then refresh the page.
If the Operations Control window is not open or crashes, open Firefox and use the address bar to open it again.
The web address is: + `http://<room-letter/number>.scaleav.us/html-frontend/operate.html`

Listen for audio problems in the room.
If you suspect there are audio problems, you may want to check other rooms first to get a feel for the baseline of what other rooms sound like.
If you determine there is an issue, then log the issue and ask Michael Proctor-Smith for help.
Examples of potential issues are,

* Hum, hiss, clicks, and pops
* Feedback
* Inaudibly low sound
* "`Hot`" audio (when audio is too loud, distortion and clipping is possible)
* Unintelligible speech

When we hear on the radio that there is an audio problem in a room, confirm whether the issue is with the camera audio or with the room's ambient sound by selecting audio track 2 (camera audio) in VLC.
If there is a problem, let the person on the radio know if the problem is with the camera audio or the room ambient audio.
If the video is also cutting out, let them know about that too.

=== Observe the Video Feed

Observe the video feed and confirm that both the PTZ Camera video and the Slides video is displaying properly.
If Video is not working then log the issue and ask Michael Proctor-Smith.
Examples of problems that could happen are:

* No slides showing: could be a problem on the speaker's end.
* Slides are cut off: the speaker may have misformatted the slides or has not configured their laptop properly to display at the correct resolution (*1024x768@60Hz*)
* Video is Choppy or it goes black: if the video goes black, make sure the projector is physically turned on, and still no picture/dark/black, then alert senior tech.

=== SCALE Signs Crashing

If there are reports of the SCALE Signs web browser crashing, press "`Restart Signs`"

=== VLC/Monitoring Station Issues

If a VLC window goes completely black, you can reload the room feed in VLC by closing the window by pressing the X in the window title bar.
A new VLC window will open in its place.

If the monitoring station computers are acting up, inform Michael Starch or Matthew Campbell

==== Last and Final Resort:

If the monitoring station computer crashes or freezes, you can restart the system:

. Windows+Shift+E to exit the i3wm window manager.
. Ask for Login Prompt
. Display the Web Control Interface by opening up Firefox and entering the web address for a room.
. New VLC windows of the various room feeds may open up stacked on top of one another, so move them around to space them out.
To Reorganize the room windows, just move them around with the mouse.
. Make sure the Audio for the VLC windows is set to Audio Track 2.
. Check that the camera is displaying in the top right corner.
