== Volunteer Logistics
:doctype: book

Here is some useful information for volunteers.

=== Communications

* *Email*: Announcements and discussions usually occur on the scale-av mailing list.
Please sign up early, as it requires approval to add your subscription.
* *Radio*: During the event we use two-way radios to stay in communication with each other in the field.
Please check out a radio from the A/V NOC.
* *Slack*: We are also encouraged to use Slack to chat.
You can download the app to your smartphone or login via your computer.
Please ask Ilan (@socallinuxexpo.org) or Bala (@socallinuxexpo.org) for an invitation, so you can access our team channels.
* *Old fashioned, offline messages*: If you're a fan of writing things on sheets of dead trees, or there's a power outage and the world is going to end but you still need to relay a message, you can leave a message at the front desk of the A/V NOC between 8am-6pm.

=== Registration

Volunteers for the A/V team will receive a free badge.
SCALE Registration for volunteers was handled by the team lead.
We submit a list of names to registration a few weeks before the conference.
You should have received an email confirming your registration for SCALE, if not, please contact Lan.

You will not be able to pick up your expo badge until the registration area has been set up late Wednesday night or Thursday morning.
The registration area is near the entrance to the Expo Hall, on the convention center side.

It is the same process for staff or attendees to pick up a badge.
You go to Registration, check-in via the bank of self-service kiosks.
If you received an email from registration, there is an express check-in code.
If you didn't get the email or misplaced it, just enter your first and last name and the email address you used to sign up as a volunteer.
The printer will print your badge and you can then pick up your shirt and swag.

After you've picked up your badge, you can check in with Lan at the A/V NOC in room 204.
We'll get you oriented.
We also have staff tshirts for the A/V team.
Please wear them when you're working.
Depending on availability, we will hand out multiple shirts so you can wear them multiple days.

=== Hotel Rooms

SCALE attendees are primarily staying at on-site Sheraton hotel or the offsite Hilton hotel 5 minutes away.

SCALE provides a small number of hotel rooms for volunteers who are working for most of the conference.
This is a privilege offered to volunteers who have done good work for us before, because we work long hours, and staying onsite is safer than a long commute.

You should have already received a confirmation email directly from the hotel, as well as an email from Ilan telling you to please contact him and not the hotel if you want to change anything about your registration.

SCALE will only cover the room and the parking.
The hotel will require a credit card on file to cover any extra charges.
Be sure to let them know if you need a parking pass.
If you don't need a car, you should consider taking Uber/Lyft to the hotel if it is under $25/each way;
that may be reimbursable with the receipt.
You should also ask about whether the room includes free internet access, and if so, what the code is.

=== Parking

Here is the general information regarding parking at the venue or around Pasadena.
You may also consider carpooling or other modes of transportation.

SCALE will handle parking reimbursement after the conference, within reason.
Please be frugal as SCALE has a lot of expenses with the new venue.

Shuttles from nearby hotels to the convention may be available.
Ask your hotel front desk for information.

=== Meals

Boxed lunches will be provided for on-site volunteers in the volunteer break room, which is Room 208.
Pastries are sometimes available in the morning.
Dinners are provided via prepaid debit-cards that reload nightly.
Outside food and beverages are not permitted in the venue.

There are many restaurants and shops around the venue, so there should be plenty of options if you want to find your own food.

Shifts

The bulk of volunteers are needed from 8am to 6pm.
We are aiming for 5-hour shifts in the morning and afternoon, which overlap around noon.This should enable you to enjoy the conference and prevent you from having too long of a day.

We will need at least one volunteer with audio mixer experience to support the evening events.
Hopefully, this duty will rotate to a different volunteer each night.

Please fill out the doodle poll to list your availability.
It is extremely easy to update your availability.

=== Training

Training will be provided onsite.
There are many veteran volunteers who can answer basic questions.
This book was created to also provide documentation of all of the procedures and equipment used by the team.

=== Questions

Lan Dang is the volunteer coordinator for the SCALE A/V Team.
Her goal is to make sure SCALE A/V is well-supported and that you have a good experience and want to come back to help out again next year.
Address all questions, concerns, and complaints to her.
